# Generated by Django 3.2.5 on 2021-08-03 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasite', '0002_rename_name_contact_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactForm',
        ),
    ]
