# Generated by Django 3.2.5 on 2021-08-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fasite', '0002_rename_name_contact_fname'),
        ('fasite', '0003_rename_contact_contactform'),
    ]

    operations = [
    ]
